added a new check for unclean index
bitcomplete/plz-cli pull request #1
Opened 2021-06-10 15:23 UTC by lyndonoc

related to [ch4816](https://app.clubhouse.io/bit-complete/story/4816/calling-plz-review-displays-index-is-not-clean)

- added another check to make sure that files that should be ignored are properly ignored using [pathspec](https://github.com/shibumi/go-pathspec) package

2021-06-10 15:44 UTC, trotterdylan requested changes
Nice work! This was trickier than I thought it was going to be 😬

2021-06-10 21:50 UTC, lyndonoc commented on actions/review.go
> +	projectIgnorePatterns, err := getIgnorePatterns("./.gitignore")
there's no issue with go-git's parsing of .gitignore, but they're coded in a way that we can't read the patterns directly from the struct.

2021-06-10 21:50 UTC, lyndonoc commented on actions/review.go
> +		for filePath := range status {
this is relative to the repository root.

2021-06-14 15:42 UTC, trotterdylan approved these changes

2021-06-14 16:16 UTC, merged